version: "2"

services:
  app1-api:
    restart: always
    image: sample-api
    build: ./samples/api
    container_name: app1-api
    environment:
      - VIRTUAL_HOST=api.app1.tomasz.xyz
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.app1.tomasz.xyz
      - LETSENCRYPT_EMAIL=tom3kr@gmail.com

  app1:
    restart: always
    image: sample-website
    build: ./samples/website
    container_name: app1
    depends_on:
      - app1-api
    volumes:
      - "./volumes/nginx-sample-website/conf.d/:/etc/nginx/conf.d"
      - "./volumes/config/sample-website/config.js:/usr/share/nginx/html/config.js"
    environment:
      - VIRTUAL_HOST=app1.tomasz.xyz
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=app1.tomasz.xyz
      - LETSENCRYPT_EMAIL=tom3kr@gmail.com
